<?php

namespace App\Enums\Stratz;

enum Hero: int
{
    case AntiMage = 1;
    case Axe = 2;
    case Bane = 3;
    case Bloodseeker = 4;
    case CrystalMaiden = 5;
    case DrowRanger = 6;
    case Earthshaker = 7;
    case Juggernaut = 8;
    case Mirana = 9;
    case Morphling = 10;
    case ShadowFiend = 11;
    case PhantomLancer = 12;
    case Puck = 13;
    case Pudge = 14;
    case Razor = 15;
    case SandKing = 16;
    case StormSpirit = 17;
    case Sven = 18;
    case Tiny = 19;
    case VengefulSpirit = 20;
    case Windranger = 21;
    case Zeus = 22;
    case Kunkka = 23;
    case Lina = 25;
    case Lion = 26;
    case ShadowShaman = 27;
    case Slardar = 28;
    case Tidehunter = 29;
    case WitchDoctor = 30;
    case Lich = 31;
    case Riki = 32;
    case Enigma = 33;
    case Tinker = 34;
    case Sniper = 35;
    case Necrophos = 36;
    case Warlock = 37;
    case Beastmaster = 38;
    case QueenOfPain = 39;
    case Venomancer = 40;
    case FacelessVoid = 41;
    case WraithKing = 42;
    case DeathProphet = 43;
    case PhantomAssassin = 44;
    case Pugna = 45;
    case TemplarAssassin = 46;
    case Viper = 47;
    case Luna = 48;
    case DragonKnight = 49;
    case Dazzle = 50;
    case Clockwerk = 51;
    case Leshrac = 52;
    case NatureSProphet = 53;
    case Lifestealer = 54;
    case DarkSeer = 55;
    case Clinkz = 56;
    case Omniknight = 57;
    case Enchantress = 58;
    case Huskar = 59;
    case NightStalker = 60;
    case Broodmother = 61;
    case BountyHunter = 62;
    case Weaver = 63;
    case Jakiro = 64;
    case Batrider = 65;
    case Chen = 66;
    case Spectre = 67;
    case AncientApparition = 68;
    case Doom = 69;
    case Ursa = 70;
    case SpiritBreaker = 71;
    case Gyrocopter = 72;
    case Alchemist = 73;
    case Invoker = 74;
    case Silencer = 75;
    case OutworldDevourer = 76;
    case Lycan = 77;
    case Brewmaster = 78;
    case ShadowDemon = 79;
    case LoneDruid = 80;
    case ChaosKnight = 81;
    case Meepo = 82;
    case TreantProtector = 83;
    case OgreMagi = 84;
    case Undying = 85;
    case Rubick = 86;
    case Disruptor = 87;
    case NyxAssassin = 88;
    case NagaSiren = 89;
    case KeeperOfTheLight = 90;
    case Io = 91;
    case Visage = 92;
    case Slark = 93;
    case Medusa = 94;
    case TrollWarlord = 95;
    case CentaurWarrunner = 96;
    case Magnus = 97;
    case Timbersaw = 98;
    case Bristleback = 99;
    case Tusk = 100;
    case SkywrathMage = 101;
    case Abaddon = 102;
    case ElderTitan = 103;
    case LegionCommander = 104;
    case Techies = 105;
    case EmberSpirit = 106;
    case EarthSpirit = 107;
    case Underlord = 108;
    case Terrorblade = 109;
    case Phoenix = 110;
    case Oracle = 111;
    case WinterWyvern = 112;
    case ArcWarden = 113;
    case MonkeyKing = 114;
    case DarkWillow = 119;
    case Pangolier = 120;
    case Grimstroke = 121;
    case Hoodwink = 123;
    case VoidSpirit = 126;
    case Snapfire = 128;
    case Mars = 129;
    case RingMaster = 131;
    case Dawnbreaker = 135;
    case Marci = 136;
    case PrimalBeast = 137;
    case Muerta = 138;
    case Kez = 145;
    case Largo = 155;

    public function title(): string
    {
        return match ($this) {
            self::AntiMage => 'Anti-Mage',
            self::Axe => 'Axe',
            self::Bane => 'Bane',
            self::Bloodseeker => 'Bloodseeker',
            self::CrystalMaiden => 'Crystal Maiden',
            self::DrowRanger => 'Drow Ranger',
            self::Earthshaker => 'Earthshaker',
            self::Juggernaut => 'Juggernaut',
            self::Mirana => 'Mirana',
            self::Morphling => 'Morphling',
            self::ShadowFiend => 'Shadow Fiend',
            self::PhantomLancer => 'Phantom Lancer',
            self::Puck => 'Puck',
            self::Pudge => 'Pudge',
            self::Razor => 'Razor',
            self::SandKing => 'Sand King',
            self::StormSpirit => 'Storm Spirit',
            self::Sven => 'Sven',
            self::Tiny => 'Tiny',
            self::VengefulSpirit => 'Vengeful Spirit',
            self::Windranger => 'Windranger',
            self::Zeus => 'Zeus',
            self::Kunkka => 'Kunkka',
            self::Lina => 'Lina',
            self::Lion => 'Lion',
            self::ShadowShaman => 'Shadow Shaman',
            self::Slardar => 'Slardar',
            self::Tidehunter => 'Tidehunter',
            self::WitchDoctor => 'Witch Doctor',
            self::Lich => 'Lich',
            self::Riki => 'Riki',
            self::Enigma => 'Enigma',
            self::Tinker => 'Tinker',
            self::Sniper => 'Sniper',
            self::Necrophos => 'Necrophos',
            self::Warlock => 'Warlock',
            self::Beastmaster => 'Beastmaster',
            self::QueenOfPain => 'Queen of Pain',
            self::Venomancer => 'Venomancer',
            self::FacelessVoid => 'Faceless Void',
            self::WraithKing => 'Wraith King',
            self::DeathProphet => 'Death Prophet',
            self::PhantomAssassin => 'Phantom Assassin',
            self::Pugna => 'Pugna',
            self::TemplarAssassin => 'Templar Assassin',
            self::Viper => 'Viper',
            self::Luna => 'Luna',
            self::DragonKnight => 'Dragon Knight',
            self::Dazzle => 'Dazzle',
            self::Clockwerk => 'Clockwerk',
            self::Leshrac => 'Leshrac',
            self::NatureSProphet => 'Nature\'s Prophet',
            self::Lifestealer => 'Lifestealer',
            self::DarkSeer => 'Dark Seer',
            self::Clinkz => 'Clinkz',
            self::Omniknight => 'Omniknight',
            self::Enchantress => 'Enchantress',
            self::Huskar => 'Huskar',
            self::NightStalker => 'Night Stalker',
            self::Broodmother => 'Broodmother',
            self::BountyHunter => 'Bounty Hunter',
            self::Weaver => 'Weaver',
            self::Jakiro => 'Jakiro',
            self::Batrider => 'Batrider',
            self::Chen => 'Chen',
            self::Spectre => 'Spectre',
            self::AncientApparition => 'Ancient Apparition',
            self::Doom => 'Doom',
            self::Ursa => 'Ursa',
            self::SpiritBreaker => 'Spirit Breaker',
            self::Gyrocopter => 'Gyrocopter',
            self::Alchemist => 'Alchemist',
            self::Invoker => 'Invoker',
            self::Silencer => 'Silencer',
            self::OutworldDevourer => 'Outworld Devourer',
            self::Lycan => 'Lycan',
            self::Brewmaster => 'Brewmaster',
            self::ShadowDemon => 'Shadow Demon',
            self::LoneDruid => 'Lone Druid',
            self::ChaosKnight => 'Chaos Knight',
            self::Meepo => 'Meepo',
            self::TreantProtector => 'Treant Protector',
            self::OgreMagi => 'Ogre Magi',
            self::Undying => 'Undying',
            self::Rubick => 'Rubick',
            self::Disruptor => 'Disruptor',
            self::NyxAssassin => 'Nyx Assassin',
            self::NagaSiren => 'Naga Siren',
            self::KeeperOfTheLight => 'Keeper of the Light',
            self::Io => 'Io',
            self::Visage => 'Visage',
            self::Slark => 'Slark',
            self::Medusa => 'Medusa',
            self::TrollWarlord => 'Troll Warlord',
            self::CentaurWarrunner => 'Centaur Warrunner',
            self::Magnus => 'Magnus',
            self::Timbersaw => 'Timbersaw',
            self::Bristleback => 'Bristleback',
            self::Tusk => 'Tusk',
            self::SkywrathMage => 'Skywrath Mage',
            self::Abaddon => 'Abaddon',
            self::ElderTitan => 'Elder Titan',
            self::LegionCommander => 'Legion Commander',
            self::Techies => 'Techies',
            self::EmberSpirit => 'Ember Spirit',
            self::EarthSpirit => 'Earth Spirit',
            self::Underlord => 'Underlord',
            self::Terrorblade => 'Terrorblade',
            self::Phoenix => 'Phoenix',
            self::Oracle => 'Oracle',
            self::WinterWyvern => 'Winter Wyvern',
            self::ArcWarden => 'Arc Warden',
            self::MonkeyKing => 'Monkey King',
            self::DarkWillow => 'Dark Willow',
            self::Pangolier => 'Pangolier',
            self::Grimstroke => 'Grimstroke',
            self::Hoodwink => 'Hoodwink',
            self::VoidSpirit => 'Void Spirit',
            self::Snapfire => 'Snapfire',
            self::Mars => 'Mars',
            self::RingMaster => 'Ring Master',
            self::Dawnbreaker => 'Dawnbreaker',
            self::Marci => 'Marci',
            self::PrimalBeast => 'Primal Beast',
            self::Muerta => 'Muerta',
            self::Kez => 'Kez',
            self::Largo => 'Largo',
        };
    }
}
